--- # copying the file
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: copying the file
      copy:
        src: /home/ansible/index.html
        dest: /home/ansible
        owner: rohit
