--- # installing jenkins
- name : installing java and jenkins
  hosts: webservers
  user: ansible
  become: true
  connection: ssh

  tasks:
    - name: installing java package
      yum:
        name: java
        state: installed

    - name: install wget command
      yum:
        name: wget
        state: installed

    - name: download jenkins package
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: download jenkins key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    
    - name: install jenkins package
      yum:
        name: jenkins
        state: installed

    - name: start jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes



