--- # onemore conditionals playbook
- hosts: all
  become: true

  tasks:
    - name: installing docker package
      yum:
        name: docker
        state: installed
      when: ansible_os_family == "RedHat"

    - name: start docker service
      service:
        name: docker
        state: started
      when: ansible_os_family == "RedHat"

    - name: install apache2 package
      apt:
        name: apache2
        state: installed
      when: ansible_os_family == "Debian"

    - name: start apache2 service
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: copy index.html file
      copy:
        src: /home/ansible/index.html
        dest: /tmp
        owner: rohit
        mode: 0666


