--- # two tasks
- hosts : all
  user: ansible
  become: true

  tasks:
    - name: installing package
      yum:
        name: httpd
        state: present

    - name: start service
      service:
        name: httpd
        state: started

