--- # reading users from external file
- hosts: webservers
  become: yes
  connection: ssh

  vars_files:
    - user.yml

  tasks:
    - name: creating user {{user2}}
      user:
        name: "{{user2}}"
